export interface IRestCategoryAction {
    type: RestCategoryActions,
    payload: Array<string>
}

export enum RestCategoryActions {
    GET_CATEGORIES_REQUESTED = "GET_CATEGORIES_REQUESTED",
    GET_CATEGORIES_DONE = "GET_CATEGORIES_DONE",
    GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED",

    POST_CATEGORIES_SENT = "POST_CATEGORIES_SENT",
    POST_CATEGORIES_DONE = "POST_CATEGORIES_DONE",
    POST_CATEGORIES_FAILED = "POST_CATEGORIES_FAILED",

    POST_CATEGORIES_CLEAN_SENT = "POST_CATEGORIES_CLEAN_SENT",
    POST_CATEGORIES_CLEAN_DONE = "POST_CATEGORIES_CLEAN_DONE",
    POST_CATEGORIES_CLEAN_FAILED = "POST_CATEGORIES_CLEAN_FAILED",

}